# .streamlit/secrets.toml
# ─────────────────────────────────────────────────────────────────
# THIS FILE CONTAINS REAL CREDENTIALS.
# It is listed in .gitignore and must NEVER be committed to GitHub.
# ─────────────────────────────────────────────────────────────────

[database]
host     = "sql12.freesqldatabase.com"
user     = "sql12829397"
password = "9RUDvPs13a"
name     = "sql12829397"



[email]
sender_email    = "onlinequizcompition@gmail.com"
app_password    = "vonbjkvtreecktva"
